export const QUESTIONS_PER_GAME = 8;

export const QUESTIONS = [
  {
    id: "space-01",
    category: "SPACE",
    difficulty: "EASY",
    prompt: "Which planet has the most moons currently confirmed?",
    options: ["Jupiter", "Saturn", "Neptune", "Uranus"],
    correctIndex: 1,
    explanation: "Saturn leads the confirmed moon count, with more than 140 known moons.",
  },
  {
    id: "nature-01",
    category: "NATURE",
    difficulty: "EASY",
    prompt: "What is the only mammal capable of true, sustained flight?",
    options: ["Flying squirrel", "Sugar glider", "Bat", "Colugo"],
    correctIndex: 2,
    explanation: "Bats generate lift with powered wingbeats; the other animals glide.",
  },
  {
    id: "science-01",
    category: "SCIENCE",
    difficulty: "MEDIUM",
    prompt: "Which element has the chemical symbol W?",
    options: ["Tungsten", "Tin", "Titanium", "Tantalum"],
    correctIndex: 0,
    explanation: "W comes from wolfram, another name for tungsten.",
  },
  {
    id: "art-01",
    category: "ART & CULTURE",
    difficulty: "MEDIUM",
    prompt: "The novel 'Things Fall Apart' was written by whom?",
    options: ["Wole Soyinka", "Chinua Achebe", "Ngugi wa Thiong'o", "Ben Okri"],
    correctIndex: 1,
    explanation: "Chinua Achebe published the novel in 1958.",
  },
  {
    id: "geography-01",
    category: "GEOGRAPHY",
    difficulty: "EASY",
    prompt: "Which city sits on two continents, Europe and Asia?",
    options: ["Cairo", "Moscow", "Istanbul", "Athens"],
    correctIndex: 2,
    explanation: "The Bosporus Strait divides Istanbul between Europe and Asia.",
  },
  {
    id: "language-01",
    category: "LANGUAGE",
    difficulty: "MEDIUM",
    prompt: "What is the dot over a lowercase 'i' or 'j' called?",
    options: ["Tittle", "Cedilla", "Macron", "Asterisk"],
    correctIndex: 0,
    explanation: "The small mark above an i or j is called a tittle.",
  },
  {
    id: "ocean-01",
    category: "OCEANS",
    difficulty: "MEDIUM",
    prompt: "What is the deepest known point in Earth's oceans?",
    options: ["Tonga Trench", "Puerto Rico Trench", "Java Trench", "Challenger Deep"],
    correctIndex: 3,
    explanation: "Challenger Deep lies in the Mariana Trench in the western Pacific.",
  },
  {
    id: "math-01",
    category: "QUICK THINKING",
    difficulty: "EASY",
    prompt: "What is the sum of the interior angles of a hexagon?",
    options: ["540°", "600°", "720°", "900°"],
    correctIndex: 2,
    explanation: "A hexagon has (6 − 2) × 180°, which equals 720°.",
  },
  {
    id: "science-02",
    category: "SCIENCE",
    difficulty: "EASY",
    prompt: "Which subatomic particle carries a negative electric charge?",
    options: ["Proton", "Neutron", "Electron", "Photon"],
    correctIndex: 2,
    explanation: "Electrons carry a negative electric charge and occupy regions around an atom's nucleus.",
  },
  {
    id: "nature-02",
    category: "NATURE",
    difficulty: "EASY",
    prompt: "What do honeybees collect from flowers to make honey?",
    options: ["Nectar", "Pollen only", "Sap", "Dew"],
    correctIndex: 0,
    explanation: "Honeybees transform flower nectar into honey inside the hive.",
  },
  {
    id: "space-02",
    category: "SPACE",
    difficulty: "EASY",
    prompt: "What is the name of the galaxy that contains our solar system?",
    options: ["Andromeda", "Milky Way", "Whirlpool", "Sombrero"],
    correctIndex: 1,
    explanation: "Our solar system is located in the Milky Way galaxy.",
  },
  {
    id: "geography-02",
    category: "GEOGRAPHY",
    difficulty: "MEDIUM",
    prompt: "The ancient city of Petra is in which modern-day country?",
    options: ["Egypt", "Jordan", "Lebanon", "Oman"],
    correctIndex: 1,
    explanation: "Petra is an archaeological city in southern Jordan.",
  },
  {
    id: "geography-03",
    category: "GEOGRAPHY",
    difficulty: "MEDIUM",
    prompt: "Mount Kilimanjaro is located in which country?",
    options: ["Kenya", "Uganda", "Tanzania", "Rwanda"],
    correctIndex: 2,
    explanation: "Mount Kilimanjaro is in northeastern Tanzania.",
  },
  {
    id: "chemistry-01",
    category: "SCIENCE",
    difficulty: "EASY",
    prompt: "What is the chemical symbol for iron?",
    options: ["Ir", "Fe", "In", "I"],
    correctIndex: 1,
    explanation: "Iron's symbol Fe comes from its Latin name, ferrum.",
  },
  {
    id: "chemistry-02",
    category: "SCIENCE",
    difficulty: "EASY",
    prompt: "Which formula represents water?",
    options: ["CO2", "O2", "H2O", "NaCl"],
    correctIndex: 2,
    explanation: "A water molecule contains two hydrogen atoms and one oxygen atom.",
  },
  {
    id: "math-02",
    category: "QUICK THINKING",
    difficulty: "EASY",
    prompt: "What is 9 multiplied by 8?",
    options: ["63", "72", "81", "74"],
    correctIndex: 1,
    explanation: "Nine groups of eight make 72.",
  },
  {
    id: "math-03",
    category: "QUICK THINKING",
    difficulty: "EASY",
    prompt: "How many degrees are in a right angle?",
    options: ["45", "90", "120", "180"],
    correctIndex: 1,
    explanation: "A right angle measures exactly 90 degrees.",
  },
  {
    id: "history-01",
    category: "HISTORY",
    difficulty: "MEDIUM",
    prompt: "Which civilization built the city of Machu Picchu?",
    options: ["Maya", "Aztec", "Inca", "Olmec"],
    correctIndex: 2,
    explanation: "Machu Picchu was built by the Inca in the Andes of Peru.",
  },
  {
    id: "history-02",
    category: "HISTORY",
    difficulty: "MEDIUM",
    prompt: "In what year did the Wright brothers make their first powered flight?",
    options: ["1895", "1903", "1914", "1927"],
    correctIndex: 1,
    explanation: "The Wright brothers' first powered flight took place in 1903.",
  },
  {
    id: "literature-01",
    category: "ART & CULTURE",
    difficulty: "EASY",
    prompt: "Who wrote the novel 'Pride and Prejudice'?",
    options: ["Mary Shelley", "Jane Austen", "Charlotte Bronte", "George Eliot"],
    correctIndex: 1,
    explanation: "Jane Austen published 'Pride and Prejudice' in 1813.",
  },
  {
    id: "culture-01",
    category: "ART & CULTURE",
    difficulty: "EASY",
    prompt: "Origami is the traditional art of folding what material?",
    options: ["Cloth", "Metal", "Paper", "Wood"],
    correctIndex: 2,
    explanation: "Origami is the Japanese art of folding paper into shapes.",
  },
  {
    id: "sports-01",
    category: "SPORTS",
    difficulty: "EASY",
    prompt: "How many players from one team are on a basketball court at a time?",
    options: ["4", "5", "6", "7"],
    correctIndex: 1,
    explanation: "Each basketball team has five players on the court at a time.",
  },
  {
    id: "sports-02",
    category: "SPORTS",
    difficulty: "EASY",
    prompt: "Wimbledon is played on which court surface?",
    options: ["Clay", "Hard court", "Grass", "Carpet"],
    correctIndex: 2,
    explanation: "Wimbledon is played on grass courts.",
  },
  {
    id: "computing-01",
    category: "TECHNOLOGY",
    difficulty: "EASY",
    prompt: "What does CPU stand for?",
    options: ["Central Processing Unit", "Computer Power Utility", "Core Program Upload", "Central Print Unit"],
    correctIndex: 0,
    explanation: "CPU stands for central processing unit, the main processor in a computer.",
  },
  {
    id: "computing-02",
    category: "TECHNOLOGY",
    difficulty: "MEDIUM",
    prompt: "What does the 'S' in HTTPS indicate?",
    options: ["Shared", "Secure", "System", "Synchronous"],
    correctIndex: 1,
    explanation: "HTTPS uses encryption, typically TLS, to secure data sent between a browser and a site.",
  },
  {
    id: "biology-02",
    category: "SCIENCE",
    difficulty: "EASY",
    prompt: "How many chambers does a human heart have?",
    options: ["Two", "Three", "Four", "Five"],
    correctIndex: 2,
    explanation: "The human heart has two atria and two ventricles.",
  },
  {
    id: "physics-01",
    category: "SCIENCE",
    difficulty: "MEDIUM",
    prompt: "What is the SI unit of electrical resistance?",
    options: ["Volt", "Watt", "Ohm", "Ampere"],
    correctIndex: 2,
    explanation: "Electrical resistance is measured in ohms, symbolized by the Greek letter omega.",
  },
  {
    id: "geography-04",
    category: "GEOGRAPHY",
    difficulty: "MEDIUM",
    prompt: "What is the world's largest island by area, excluding continents?",
    options: ["Borneo", "Madagascar", "Greenland", "New Guinea"],
    correctIndex: 2,
    explanation: "Greenland is the largest island when continents are excluded.",
  },
  {
    id: "nature-03",
    category: "NATURE",
    difficulty: "EASY",
    prompt: "Which animal is the fastest land runner?",
    options: ["Pronghorn", "Cheetah", "Lion", "Ostrich"],
    correctIndex: 1,
    explanation: "The cheetah is the fastest land animal over short distances.",
  },
  {
    id: "science-03",
    category: "SCIENCE",
    difficulty: "EASY",
    prompt: "What is the central part of an atom called?",
    options: ["Nucleus", "Electron shell", "Molecule", "Isotope"],
    correctIndex: 0,
    explanation: "An atom's nucleus contains its protons and neutrons.",
  },
  {
    id: "science-04",
    category: "SCIENCE",
    difficulty: "EASY",
    prompt: "What is the chemical symbol for sodium?",
    options: ["So", "S", "Na", "N"],
    correctIndex: 2,
    explanation: "Sodium's chemical symbol is Na, from the Latin natrium.",
  },
  {
    id: "biology-03",
    category: "SCIENCE",
    difficulty: "MEDIUM",
    prompt: "Which plant tissue transports water from roots toward leaves?",
    options: ["Phloem", "Xylem", "Epidermis", "Pollen"],
    correctIndex: 1,
    explanation: "Xylem carries water and dissolved minerals upward through a plant.",
  },
  {
    id: "math-04",
    category: "QUICK THINKING",
    difficulty: "EASY",
    prompt: "What is the square root of 144?",
    options: ["10", "11", "12", "14"],
    correctIndex: 2,
    explanation: "Twelve multiplied by twelve equals 144.",
  },
  {
    id: "computing-03",
    category: "TECHNOLOGY",
    difficulty: "MEDIUM",
    prompt: "In base two, what number does the binary value 10 represent?",
    options: ["1", "2", "10", "16"],
    correctIndex: 1,
    explanation: "The binary digits 10 represent decimal two.",
  },
  {
    id: "science-05",
    category: "SCIENCE",
    difficulty: "EASY",
    prompt: "A solution with a pH below 7 is generally described as what?",
    options: ["Acidic", "Neutral", "Basic", "Saline"],
    correctIndex: 0,
    explanation: "On the standard pH scale, values below 7 are acidic.",
  },
  {
    id: "science-06",
    category: "SCIENCE",
    difficulty: "EASY",
    prompt: "Which gas do plants take in during photosynthesis?",
    options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Helium"],
    correctIndex: 1,
    explanation: "Plants take in carbon dioxide and use light energy to make sugars.",
  },
  {
    id: "geography-05",
    category: "GEOGRAPHY",
    difficulty: "EASY",
    prompt: "Which ocean borders the east coast of Africa?",
    options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Southern Ocean"],
    correctIndex: 1,
    explanation: "The Indian Ocean lies along Africa's eastern coast.",
  },
  {
    id: "culture-02",
    category: "ART & CULTURE",
    difficulty: "EASY",
    prompt: "Which language is the primary official language of Brazil?",
    options: ["Spanish", "Portuguese", "French", "Italian"],
    correctIndex: 1,
    explanation: "Portuguese is Brazil's official language.",
  },
  {
    id: "biology-04",
    category: "SCIENCE",
    difficulty: "EASY",
    prompt: "What is the largest organ of the human body?",
    options: ["Liver", "Lung", "Skin", "Heart"],
    correctIndex: 2,
    explanation: "The skin is the body's largest organ by surface area and weight.",
  },
  {
    id: "geography-06",
    category: "GEOGRAPHY",
    difficulty: "EASY",
    prompt: "What is the capital city of Ghana?",
    options: ["Kumasi", "Accra", "Tamale", "Cape Coast"],
    correctIndex: 1,
    explanation: "Accra is Ghana's capital and largest city.",
  },
];