export const QUESTIONS = [
  {
    id: "space-01",
    category: "SPACE",
    difficulty: "EASY",
    prompt: "Which planet has the most moons currently confirmed?",
    options: ["Jupiter", "Saturn", "Neptune", "Uranus"],
    correctIndex: 1,
    explanation: "Saturn leads the confirmed moon count, with more than 140 known moons.",
  },
  {
    id: "nature-01",
    category: "NATURE",
    difficulty: "EASY",
    prompt: "What is the only mammal capable of true, sustained flight?",
    options: ["Flying squirrel", "Sugar glider", "Bat", "Colugo"],
    correctIndex: 2,
    explanation: "Bats generate lift with powered wingbeats; the other animals glide.",
  },
  {
    id: "science-01",
    category: "SCIENCE",
    difficulty: "MEDIUM",
    prompt: "Which element has the chemical symbol W?",
    options: ["Tungsten", "Tin", "Titanium", "Tantalum"],
    correctIndex: 0,
    explanation: "W comes from wolfram, another name for tungsten.",
  },
  {
    id: "art-01",
    category: "ART & CULTURE",
    difficulty: "MEDIUM",
    prompt: "The novel 'Things Fall Apart' was written by whom?",
    options: ["Wole Soyinka", "Chinua Achebe", "Ngugi wa Thiong'o", "Ben Okri"],
    correctIndex: 1,
    explanation: "Chinua Achebe published the novel in 1958.",
  },
  {
    id: "geography-01",
    category: "GEOGRAPHY",
    difficulty: "EASY",
    prompt: "Which city sits on two continents, Europe and Asia?",
    options: ["Cairo", "Moscow", "Istanbul", "Athens"],
    correctIndex: 2,
    explanation: "The Bosporus Strait divides Istanbul between Europe and Asia.",
  },
  {
    id: "language-01",
    category: "LANGUAGE",
    difficulty: "MEDIUM",
    prompt: "What is the dot over a lowercase 'i' or 'j' called?",
    options: ["Tittle", "Cedilla", "Macron", "Asterisk"],
    correctIndex: 0,
    explanation: "The small mark above an i or j is called a tittle.",
  },
  {
    id: "ocean-01",
    category: "OCEANS",
    difficulty: "MEDIUM",
    prompt: "What is the deepest known point in Earth's oceans?",
    options: ["Tonga Trench", "Puerto Rico Trench", "Java Trench", "Challenger Deep"],
    correctIndex: 3,
    explanation: "Challenger Deep lies in the Mariana Trench in the western Pacific.",
  },
  {
    id: "math-01",
    category: "QUICK THINKING",
    difficulty: "EASY",
    prompt: "What is the sum of the interior angles of a hexagon?",
    options: ["540°", "600°", "720°", "900°"],
    correctIndex: 2,
    explanation: "A hexagon has (6 − 2) × 180°, which equals 720°.",
  },
];